# Copyright 2023-2024 Logan Magee
#
# SPDX-License-Identifier: LicenseRef-Proprietary

name: Check code

on: [push, pull_request]

env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - run: cargo clippy --all-targets --all-features
      - run: cargo test --all-features
      - run: cargo fmt --check
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - uses: gradle/actions/setup-gradle@v4
      - run: rustup target add aarch64-linux-android x86_64-linux-android
      - run: ./gradlew build
      - run: ./gradlew dokkaHtml
