# Copyright 2023-2024 Logan Magee
#
# SPDX-License-Identifier: Apache-2.0

name: Check code

on: [push, pull_request]

permissions:
  contents: read

env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          lfs: true
      - run: cargo clippy --all-targets --all-features
      - run: cargo test --all-features
      - run: cargo fmt --check
      - uses: actions/setup-java@c1e323688fd81a25caa38c78aa6df2d33d3e20d9 # v4.8.0
        with:
          distribution: temurin
          java-version: 21
      - uses: gradle/actions/setup-gradle@ed408507eac070d1f99cc633dbcf757c94c7933a # v4.4.3
      - run: rustup target add aarch64-linux-android x86_64-linux-android
      - run: ./gradlew build
      - run: ./gradlew dokkaGeneratePublicationHtml
