# Copyright 2023-2024 Logan Magee
#
# SPDX-License-Identifier: MPL-2.0

name: Check licensing

on: [push, pull_request]

permissions:
  contents: read

jobs:
  license-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: fsfe/reuse-action@v5
