# Copyright 2023-2024 Logan Magee
#
# SPDX-License-Identifier: LicenseRef-Proprietary

name: Check licensing

on: [push, pull_request]

jobs:
  license-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: fsfe/reuse-action@v3
